spring:
  application:
    name: tom-user-login-rest-apis
  datasource:
    url: jdbc:mysql://localhost:3306/user-login-db
    username: tom
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate #control how Hibernate manages db schema at startup - only check that the schema matches entities
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true #run flyway on startup
    locations: classpath:db/migration
    validate-on-migrate: true #validate checksum of applied migrations - fails if files were changed after being applied
  main:
    banner-mode: off

server:
  port: 8080

logging:
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %blue(%-5level) %magenta(${PID:- }) --- %red([%15.15thread]) %yellow(%-40.40logger{39}): %msg%n%wEx"
  level:
    org.tommap.tomuserloginrestapis: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: ${JWT_SECRET:f27f63142c9dedc3ee9557f3278e0ca0fe70b2f51d003e55e6b92d6437e1ffb0} #hash value tom-secret-key
  expiration: ${JWT_EXPIRATION:3600000} #milisecond